package com.GuoGuo.JuicyChat.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.


import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

@Entity
public class Friend implements Parcelable {
	@Id
	private long id;
	
	private String myid;
	private String friendid;
	private String remark;
	private int isblacklist;
	private int isnonotice;
	private String username;
	private String nickname;
	private String headico;
	private String createtime;
	private int sex;
	private int state;//1好友   3被加
	private String letter;
	private String whatsup;
	private int isvisible;
	
	public long getId() {
		return id;
	}
	
	public void setId(long id) {
		this.id = id;
	}
	
	public String getMyid() {
		return myid;
	}
	
	public void setMyid(String myid) {
		this.myid = myid;
	}
	
	public String getFriendid() {
		return friendid;
	}
	
	public void setFriendid(String friendid) {
		this.friendid = friendid;
	}
	
	public String getRemark() {
		return remark;
	}
	
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public int getIsblacklist() {
		return isblacklist;
	}
	
	public void setIsblacklist(int isblacklist) {
		this.isblacklist = isblacklist;
	}
	
	public int getIsnonotice() {
		return isnonotice;
	}
	
	public void setIsnonotice(int isnonotice) {
		this.isnonotice = isnonotice;
	}
	
	public String getUsername() {
		return username;
	}
	
	public void setUsername(String username) {
		this.username = username;
	}
	
	public String getNickname() {
		return nickname;
	}
	
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}
	
	public String getHeadico() {
		return headico;
	}
	
	public void setHeadico(String headico) {
		this.headico = headico;
	}
	
	public String getCreatetime() {
		return createtime;
	}
	
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}
	
	public int getSex() {
		return sex;
	}
	
	public void setSex(int sex) {
		this.sex = sex;
	}
	
	public int getState() {
		return state;
	}
	
	public void setState(int state) {
		this.state = state;
	}
	
	public String getLetter() {
		return letter;
	}
	
	public void setLetter(String letter) {
		this.letter = letter;
	}
	
	public String getWhatsup() {
		return whatsup;
	}
	
	public void setWhatsup(String whatsup) {
		this.whatsup = whatsup;
	}
	
	public int getIsvisible() {
		return isvisible;
	}
	
	public void setIsvisible(int isvisible) {
		this.isvisible = isvisible;
	}
	
	public Friend() {
	}
	
	public Friend(String friendid, String nickname, String headico) {
		this.friendid = friendid;
		this.nickname = nickname;
		this.headico = headico;
	}
	
	@Generated(hash = 165268151)
	public Friend(long id, String myid, String friendid, String remark, int isblacklist, int isnonotice, String username, String nickname, String headico, String createtime, int sex, int state, String letter, String whatsup, int isvisible) {
		this.id = id;
		this.myid = myid;
		this.friendid = friendid;
		this.remark = remark;
		this.isblacklist = isblacklist;
		this.isnonotice = isnonotice;
		this.username = username;
		this.nickname = nickname;
		this.headico = headico;
		this.createtime = createtime;
		this.sex = sex;
		this.state = state;
		this.letter = letter;
		this.whatsup = whatsup;
		this.isvisible = isvisible;
	}

	@Override
	public int describeContents() {
		return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(this.id);
		dest.writeString(this.myid);
		dest.writeString(this.friendid);
		dest.writeString(this.remark);
		dest.writeInt(this.isblacklist);
		dest.writeInt(this.isnonotice);
		dest.writeString(this.username);
		dest.writeString(this.nickname);
		dest.writeString(this.headico);
		dest.writeString(this.createtime);
		dest.writeInt(this.sex);
		dest.writeInt(this.state);
		dest.writeString(this.letter);
		dest.writeString(this.whatsup);
		dest.writeInt(this.isvisible);
	}
	
	protected Friend(Parcel in) {
		this.id = in.readLong();
		this.myid = in.readString();
		this.friendid = in.readString();
		this.remark = in.readString();
		this.isblacklist = in.readInt();
		this.isnonotice = in.readInt();
		this.username = in.readString();
		this.nickname = in.readString();
		this.headico = in.readString();
		this.createtime = in.readString();
		this.sex = in.readInt();
		this.state = in.readInt();
		this.letter = in.readString();
		this.whatsup = in.readString();
		this.isvisible = in.readInt();
	}
	
	public static final Creator<Friend> CREATOR = new Creator<Friend>() {
		@Override
		public Friend createFromParcel(Parcel source) {
			return new Friend(source);
		}
		
		@Override
		public Friend[] newArray(int size) {
			return new Friend[size];
		}
	};
}
