package com.kuaishou.hb.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

/**
 * Entity mapped to table GROUPS.
 */
@Entity
public class Groups implements Parcelable {
	private String id;
	@Id
	private String groupid;
	private String userid;
	private String groupname;
	private double redpacketlimit;
	private double locklimit;
	private String grouphead;
	private String username;
	private String nickname;
	private String userhead;
	private int sex;
	private String leaderid;
	private int isnonotice;
	private String gonggao;
	private int iscanadduser;
	private String remark;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGroupid() {
		return groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getGroupname() {
		return groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}
	
	public double getRedpacketlimit() {
		return redpacketlimit;
	}
	
	public void setRedpacketlimit(double redpacketlimit) {
		this.redpacketlimit = redpacketlimit;
	}
	
	public double getLocklimit() {
		return locklimit;
	}
	
	public void setLocklimit(double locklimit) {
		this.locklimit = locklimit;
	}

	public String getGrouphead() {
		return grouphead;
	}

	public void setGrouphead(String grouphead) {
		this.grouphead = grouphead;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getUserhead() {
		return userhead;
	}

	public void setUserhead(String userhead) {
		this.userhead = userhead;
	}

	public int getSex() {
		return sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public String getLeaderid() {
		return leaderid;
	}

	public void setLeaderid(String leaderid) {
		this.leaderid = leaderid;
	}

	public int getIsnonotice() {
		return isnonotice;
	}

	public void setIsnonotice(int isnonotice) {
		this.isnonotice = isnonotice;
	}

	public String getGonggao() {
		return gonggao;
	}

	public void setGonggao(String gonggao) {
		this.gonggao = gonggao;
	}

	public int getIscanadduser() {
		return iscanadduser;
	}

	public void setIscanadduser(int iscanadduser) {
		this.iscanadduser = iscanadduser;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Groups() {
	}

	@Override
	public int describeContents() {
		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeString(this.id);
		dest.writeString(this.groupid);
		dest.writeString(this.userid);
		dest.writeString(this.groupname);
		dest.writeDouble(this.redpacketlimit);
		dest.writeDouble(this.locklimit);
		dest.writeString(this.grouphead);
		dest.writeString(this.username);
		dest.writeString(this.nickname);
		dest.writeString(this.userhead);
		dest.writeInt(this.sex);
		dest.writeString(this.leaderid);
		dest.writeInt(this.isnonotice);
		dest.writeString(this.gonggao);
		dest.writeInt(this.iscanadduser);
		dest.writeString(this.remark);
	}

	protected Groups(Parcel in) {
		this.id = in.readString();
		this.groupid = in.readString();
		this.userid = in.readString();
		this.groupname = in.readString();
		this.redpacketlimit = in.readDouble();
		this.locklimit = in.readDouble();
		this.grouphead = in.readString();
		this.username = in.readString();
		this.nickname = in.readString();
		this.userhead = in.readString();
		this.sex = in.readInt();
		this.leaderid = in.readString();
		this.isnonotice = in.readInt();
		this.gonggao = in.readString();
		this.iscanadduser = in.readInt();
		this.remark = in.readString();
	}
	
	@Generated(hash = 1713503368)
	public Groups(String id, String groupid, String userid, String groupname, double redpacketlimit,
	              double locklimit, String grouphead, String username, String nickname, String userhead, int sex,
	              String leaderid, int isnonotice, String gonggao, int iscanadduser, String remark) {
		this.id = id;
		this.groupid = groupid;
		this.userid = userid;
		this.groupname = groupname;
		this.redpacketlimit = redpacketlimit;
		this.locklimit = locklimit;
		this.grouphead = grouphead;
		this.username = username;
		this.nickname = nickname;
		this.userhead = userhead;
		this.sex = sex;
		this.leaderid = leaderid;
		this.isnonotice = isnonotice;
		this.gonggao = gonggao;
		this.iscanadduser = iscanadduser;
		this.remark = remark;
	}

	public static final Creator<Groups> CREATOR = new Creator<Groups>() {
		@Override
		public Groups createFromParcel(Parcel source) {
			return new Groups(source);
		}

		@Override
		public Groups[] newArray(int size) {
			return new Groups[size];
		}
	};
}
